#开发环境
breakpoint:
  upload:
    dir: C:/data0/uploads/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880

spring:
  redis:
    host: 192.168.179.128
    port: 6379
    password: 
    pool:
      max-active: 30
      max-idle: 10
      max-wait: 10000
    timeout: 0
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
